# -*- coding: utf-8 -*-
"""
Problem 45 - Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle        T(n) = n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      P(n) = n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal       H(n) = n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from common.sequences import triangles, pentagonals, hexagonals


def solution():
    # H increases faster than P and T, which ensures less checks -- i.e.,
    # a faster solution
    for h in hexagonals[143:]:
        if h in triangles and h in pentagonals:
            return h


if __name__ == '__main__':
    print(solution())
